import { ArrayItemActions, moveArrayItem, EditorInput, EditorTextarea } from "../../authoring-primitives.tsx";
import { standardEditorStyles } from "../../standard-editor-styles.ts";
import type { TemplateAuthoringCapability, TemplateAuthoringEditorProps } from "../../types.ts";

export function FreeAuthoringEditor({ data, onValue }: TemplateAuthoringEditorProps) {
  const blocks = Array.isArray(data.内容) ? data.内容 as Record<string, unknown>[] : [];
  const emptyBlock = { 名称: "新内容", 原文: "", 描述: "" };
  const update = (index: number, path: string, value: string) => onValue("内容", blocks.map((item, row) => row === index ? { ...item, [path]: value } : item));
  return <div className="template-owned-editor free-editor"><style>{standardEditorStyles + `.free-editor .free-basics{grid-template-columns:repeat(3,minmax(0,1fr))}.free-editor .free-blocks{container-type:inline-size;display:flex;flex-direction:column;gap:8px}.free-blocks>header{display:flex;align-items:center;justify-content:space-between}.free-blocks h3{margin:0;color:#6f2024;font-size:16px}.free-editor-block{display:grid;grid-template-columns:minmax(0,1.3fr) minmax(0,1.3fr) auto;gap:8px;padding:8px 10px;border:1px solid #d8cec0;background:#fffaf2}.free-block-description{grid-column:1/-1}@container(max-width:360px){.free-editor-block{grid-template-columns:repeat(2,minmax(0,1fr))}.free-block-description{grid-column:1/-1}}@media(max-width:760px){.free-editor .free-basics{grid-template-columns:minmax(0,1fr)}}`}</style>
    <section className="free-basics"><EditorInput label="名称" value={data.名称} onChange={(value) => onValue("名称", value)} /><EditorInput label="原文" value={data.原文} onChange={(value) => onValue("原文", value)} /><EditorInput label="类型" value={data.类型} onChange={(value) => onValue("类型", value)} /><div className="template-editor-span-all"><EditorTextarea label="简介" value={data.简介} onChange={(value) => onValue("简介", value)} /></div></section>
    <section className="free-blocks"><header><h3>内容块</h3><button type="button" onClick={() => onValue("内容", [...blocks, { ...emptyBlock }])}>＋ 新增</button></header>{blocks.map((block, index) => <article className="free-editor-block" key={index}><EditorInput label="名称" value={block.名称} onChange={(value) => update(index, "名称", value)} /><EditorInput label="原文" value={block.原文} onChange={(value) => update(index, "原文", value)} /><ArrayItemActions item={block} index={index} count={blocks.length} onClear={() => onValue("内容", blocks.map((item, row) => row === index ? { ...emptyBlock } : item))} onDelete={() => onValue("内容", blocks.filter((_, row) => row !== index))} onMove={(offset) => onValue("内容", moveArrayItem(blocks, index, offset))} /><div className="free-block-description"><EditorTextarea label="描述" value={block.描述} onChange={(value) => update(index, "描述", value)} /></div></article>)}</section>
  </div>;
}
export const freeAuthoring: TemplateAuthoringCapability = { templateId: "自由", templateVersion: "1.0.0", Editor: FreeAuthoringEditor };
