import { ArrayItemActions, moveArrayItem, EditorInput, EditorTextarea } from "../../authoring-primitives.tsx";
import { standardEditorStyles } from "../../standard-editor-styles.ts";
import type { TemplateAuthoringCapability, TemplateAuthoringEditorProps } from "../../types.ts";

export function EnvironmentAuthoringEditor({ data, onValue }: TemplateAuthoringEditorProps) {
  const features = Array.isArray(data.特性) ? data.特性 as Record<string, unknown>[] : [];
  const update = (index: number, path: string, value: string) => onValue("特性", features.map((item, row) => row === index ? { ...item, [path]: value } : item));
  const field = (path: string, options?: readonly string[]) => <EditorInput label={path} value={data[path]} options={options} onChange={(value) => onValue(path, value)} />;
  return <div className="template-owned-editor environment-editor"><style>{standardEditorStyles + `.environment-editor .identity{grid-template-columns:repeat(3,minmax(0,1fr))}.environment-editor .setting{grid-template-columns:repeat(2,minmax(0,1fr))}.environment-feature{grid-column:1/-1;display:grid;grid-template-columns:repeat(3,minmax(0,1fr)) auto;gap:8px;padding:8px 10px;border:1px solid #d8cec0;background:#fffaf2}.environment-feature .wide{grid-column:1/-1}@media(max-width:760px){.environment-feature{grid-template-columns:minmax(0,1fr)}.environment-feature .wide{grid-column:1}}`}</style>
    <section className="identity">{field("名称")}{field("类型")}{<EditorInput label="原文" value={data.原文} onChange={(value) => onValue("原文", value)} />}{field("位阶", ["1", "2", "3", "4"])}{field("种类", ["探索", "险境", "社交", "事件"])}</section>
    <section className="setting"><div className="template-editor-span-all"><EditorTextarea label="简介" value={data.简介} onChange={(value) => onValue("简介", value)} /></div><div className="template-editor-span-all"><EditorTextarea label="趋向" value={data.趋向} onChange={(value) => onValue("趋向", value)} /></div>{field("难度")}<EditorTextarea label="潜在敌人" value={data.潜在敌人} onChange={(value) => onValue("潜在敌人", value)} /></section>
    <section><header><h3>特性</h3><button type="button" onClick={() => onValue("特性", [...features, { 特性名称: "新特性", 特性原文: "", 特性类型: "", 特性描述: "", 引导问题: "" }])}>＋ 新增</button></header>{features.map((feature, index) => <article className="environment-feature" key={index}><EditorInput label="特性名称" value={feature.特性名称} onChange={(value) => update(index, "特性名称", value)} /><EditorInput label="特性原文" value={feature.特性原文} onChange={(value) => update(index, "特性原文", value)} /><EditorInput label="特性类型" value={feature.特性类型} options={["被动", "动作", "反应"]} onChange={(value) => update(index, "特性类型", value)} /><ArrayItemActions item={feature} index={index} count={features.length} onClear={() => onValue("特性", features.map((item, row) => row === index ? { 特性名称: "新特性", 特性原文: "", 特性类型: "", 特性描述: "", 引导问题: "" } : item))} onDelete={() => onValue("特性", features.filter((_, row) => row !== index))} onMove={(offset) => onValue("特性", moveArrayItem(features, index, offset))} /><div className="wide"><EditorTextarea label="特性描述" value={feature.特性描述} onChange={(value) => update(index, "特性描述", value)} /></div><div className="wide"><EditorTextarea label="引导问题" value={feature.引导问题} onChange={(value) => update(index, "引导问题", value)} /></div></article>)}</section>
  </div>;
}
export const environmentAuthoring: TemplateAuthoringCapability = { templateId: "环境", templateVersion: "1.0.0", Editor: EnvironmentAuthoringEditor };
