import { retryTemplateImport } from "../core/retry-import.ts";
import type { TrustedTemplateRenderer } from "./template-frontend-registry.ts";
import type { TemplateAuthoringCapability } from "./types.ts";

export type TemplateFrontendManifestEntry = {
  templateId: string;
  templateVersion: string;
  loadRenderer: () => Promise<TrustedTemplateRenderer>;
  loadAuthoring: () => Promise<TemplateAuthoringCapability>;
  stableReferenceCard: boolean;
};

export const templateFrontendManifest: readonly TemplateFrontendManifestEntry[] = [
  entry("玩家卡", "1.0.0", () => retryTemplateImport("./player-card/1.0.0/renderer.tsx", () => import("./player-card/1.0.0/renderer.tsx")).then((module) => module.playerCardRendererRevision), () => retryTemplateImport("./player-card/1.0.0/authoring-editor.tsx", () => import("./player-card/1.0.0/authoring-editor.tsx")).then((module) => module.playerCardAuthoring)),
  entry("敌人", "1.1.0", () => retryTemplateImport("./adversary/1.1.0/renderer.tsx", () => import("./adversary/1.1.0/renderer.tsx")).then((module) => module.adversaryRendererRevision), () => retryTemplateImport("./adversary/1.1.0/authoring-editor.tsx", () => import("./adversary/1.1.0/authoring-editor.tsx")).then((module) => module.adversaryAuthoring)),
  entry("种族", "1.1.0", () => retryTemplateImport("./ancestry/1.1.0/renderer.tsx", () => import("./ancestry/1.1.0/renderer.tsx")).then((module) => module.ancestryRendererRevision), () => retryTemplateImport("./ancestry/1.1.0/authoring-editor.tsx", () => import("./ancestry/1.1.0/authoring-editor.tsx")).then((module) => module.ancestryAuthoring), true),
  entry("护甲", "1.1.0", () => retryTemplateImport("./armor/1.1.0/renderer.tsx", () => import("./armor/1.1.0/renderer.tsx")).then((module) => module.armorRendererRevision), () => retryTemplateImport("./armor/1.1.0/authoring-editor.tsx", () => import("./armor/1.1.0/authoring-editor.tsx")).then((module) => module.armorAuthoring)),
  entry("社群", "1.1.0", () => retryTemplateImport("./community/1.1.0/renderer.tsx", () => import("./community/1.1.0/renderer.tsx")).then((module) => module.communityRendererRevision), () => retryTemplateImport("./community/1.1.0/authoring-editor.tsx", () => import("./community/1.1.0/authoring-editor.tsx")).then((module) => module.communityAuthoring), true),
  entry("领域卡", "1.1.0", () => retryTemplateImport("./domain/1.1.0/renderer.tsx", () => import("./domain/1.1.0/renderer.tsx")).then((module) => module.domainRendererRevision), () => retryTemplateImport("./domain/1.1.0/authoring-editor.tsx", () => import("./domain/1.1.0/authoring-editor.tsx")).then((module) => module.domainAuthoring), true),
  entry("环境", "1.1.0", () => retryTemplateImport("./environment/1.1.0/renderer.tsx", () => import("./environment/1.1.0/renderer.tsx")).then((module) => module.environmentRendererRevision), () => retryTemplateImport("./environment/1.1.0/authoring-editor.tsx", () => import("./environment/1.1.0/authoring-editor.tsx")).then((module) => module.environmentAuthoring)),
  entry("自由", "1.1.0", () => retryTemplateImport("./free/1.1.0/renderer.tsx", () => import("./free/1.1.0/renderer.tsx")).then((module) => module.freeRendererRevision), () => retryTemplateImport("./free/1.1.0/authoring-editor.tsx", () => import("./free/1.1.0/authoring-editor.tsx")).then((module) => module.freeAuthoring)),
  entry("物品", "1.1.0", () => retryTemplateImport("./item/1.1.0/renderer.tsx", () => import("./item/1.1.0/renderer.tsx")).then((module) => module.itemRendererRevision), () => retryTemplateImport("./item/1.1.0/authoring-editor.tsx", () => import("./item/1.1.0/authoring-editor.tsx")).then((module) => module.itemAuthoring), true),
  entry("职业", "1.1.0", () => retryTemplateImport("./profession/1.1.0/renderer.tsx", () => import("./profession/1.1.0/renderer.tsx")).then((module) => module.professionRendererRevision), () => retryTemplateImport("./profession/1.1.0/authoring-editor.tsx", () => import("./profession/1.1.0/authoring-editor.tsx")).then((module) => module.professionAuthoring), true),
  entry("子职业", "1.1.0", () => retryTemplateImport("./subclass/1.1.0/renderer.tsx", () => import("./subclass/1.1.0/renderer.tsx")).then((module) => module.subclassRendererRevision), () => retryTemplateImport("./subclass/1.1.0/authoring-editor.tsx", () => import("./subclass/1.1.0/authoring-editor.tsx")).then((module) => module.subclassAuthoring), true),
  entry("武器", "1.1.0", () => retryTemplateImport("./weapon/1.1.0/renderer.tsx", () => import("./weapon/1.1.0/renderer.tsx")).then((module) => module.weaponRendererRevision), () => retryTemplateImport("./weapon/1.1.0/authoring-editor.tsx", () => import("./weapon/1.1.0/authoring-editor.tsx")).then((module) => module.weaponAuthoring)),
  entry("敌人", "1.0.0", () => retryTemplateImport("./adversary/1.0.0/renderer.tsx", () => import("./adversary/1.0.0/renderer.tsx")).then((module) => module.adversaryRendererRevision), () => retryTemplateImport("./adversary/1.0.0/authoring-editor.tsx", () => import("./adversary/1.0.0/authoring-editor.tsx")).then((module) => module.adversaryAuthoring)),
  entry("种族", "1.0.0", () => retryTemplateImport("./ancestry/1.0.0/renderer.tsx", () => import("./ancestry/1.0.0/renderer.tsx")).then((module) => module.ancestryRendererRevision), () => retryTemplateImport("./ancestry/1.0.0/authoring-editor.tsx", () => import("./ancestry/1.0.0/authoring-editor.tsx")).then((module) => module.ancestryAuthoring), true),
  entry("护甲", "1.0.0", () => retryTemplateImport("./armor/1.0.0/renderer.tsx", () => import("./armor/1.0.0/renderer.tsx")).then((module) => module.armorRendererRevision), () => retryTemplateImport("./armor/1.0.0/authoring-editor.tsx", () => import("./armor/1.0.0/authoring-editor.tsx")).then((module) => module.armorAuthoring)),
  entry("社群", "1.0.0", () => retryTemplateImport("./community/1.0.0/renderer.tsx", () => import("./community/1.0.0/renderer.tsx")).then((module) => module.communityRendererRevision), () => retryTemplateImport("./community/1.0.0/authoring-editor.tsx", () => import("./community/1.0.0/authoring-editor.tsx")).then((module) => module.communityAuthoring), true),
  entry("领域卡", "1.0.0", () => retryTemplateImport("./domain/1.0.0/renderer.tsx", () => import("./domain/1.0.0/renderer.tsx")).then((module) => module.domainRendererRevision), () => retryTemplateImport("./domain/1.0.0/authoring-editor.tsx", () => import("./domain/1.0.0/authoring-editor.tsx")).then((module) => module.domainAuthoring), true),
  entry("环境", "1.0.0", () => retryTemplateImport("./environment/1.0.0/renderer.tsx", () => import("./environment/1.0.0/renderer.tsx")).then((module) => module.environmentRendererRevision), () => retryTemplateImport("./environment/1.0.0/authoring-editor.tsx", () => import("./environment/1.0.0/authoring-editor.tsx")).then((module) => module.environmentAuthoring)),
  entry("自由", "1.0.0", () => retryTemplateImport("./free/1.0.0/renderer.tsx", () => import("./free/1.0.0/renderer.tsx")).then((module) => module.freeRendererRevision), () => retryTemplateImport("./free/1.0.0/authoring-editor.tsx", () => import("./free/1.0.0/authoring-editor.tsx")).then((module) => module.freeAuthoring)),
  entry("物品", "1.0.0", () => retryTemplateImport("./item/1.0.0/renderer.tsx", () => import("./item/1.0.0/renderer.tsx")).then((module) => module.itemRendererRevision), () => retryTemplateImport("./item/1.0.0/authoring-editor.tsx", () => import("./item/1.0.0/authoring-editor.tsx")).then((module) => module.itemAuthoring), true),
  entry("职业", "1.0.0", () => retryTemplateImport("./profession/1.0.0/renderer.tsx", () => import("./profession/1.0.0/renderer.tsx")).then((module) => module.professionRendererRevision), () => retryTemplateImport("./profession/1.0.0/authoring-editor.tsx", () => import("./profession/1.0.0/authoring-editor.tsx")).then((module) => module.professionAuthoring), true),
  entry("子职业", "1.0.0", () => retryTemplateImport("./subclass/1.0.0/renderer.tsx", () => import("./subclass/1.0.0/renderer.tsx")).then((module) => module.subclassRendererRevision), () => retryTemplateImport("./subclass/1.0.0/authoring-editor.tsx", () => import("./subclass/1.0.0/authoring-editor.tsx")).then((module) => module.subclassAuthoring), true),
  entry("武器", "1.0.0", () => retryTemplateImport("./weapon/1.0.0/renderer.tsx", () => import("./weapon/1.0.0/renderer.tsx")).then((module) => module.weaponRendererRevision), () => retryTemplateImport("./weapon/1.0.0/authoring-editor.tsx", () => import("./weapon/1.0.0/authoring-editor.tsx")).then((module) => module.weaponAuthoring)),
  entry("敌人", "1.0.1", () => retryTemplateImport("./adversary/1.0.1/renderer.tsx", () => import("./adversary/1.0.1/renderer.tsx")).then((module) => module.adversaryRendererRevision), () => retryTemplateImport("./adversary/1.0.1/authoring-editor.tsx", () => import("./adversary/1.0.1/authoring-editor.tsx")).then((module) => module.adversaryAuthoring)),
  entry("敌人", "1.0.2", () => retryTemplateImport("./adversary/1.0.2/renderer.tsx", () => import("./adversary/1.0.2/renderer.tsx")).then((module) => module.adversaryRendererRevision), () => retryTemplateImport("./adversary/1.0.2/authoring-editor.tsx", () => import("./adversary/1.0.2/authoring-editor.tsx")).then((module) => module.adversaryAuthoring)),
  entry("敌人", "1.0.3", () => retryTemplateImport("./adversary/1.0.3/renderer.tsx", () => import("./adversary/1.0.3/renderer.tsx")).then((module) => module.adversaryRendererRevision), () => retryTemplateImport("./adversary/1.0.3/authoring-editor.tsx", () => import("./adversary/1.0.3/authoring-editor.tsx")).then((module) => module.adversaryAuthoring)),
  entry("敌人", "1.0.4", () => retryTemplateImport("./adversary/1.0.4/renderer.tsx", () => import("./adversary/1.0.4/renderer.tsx")).then((module) => module.adversaryRendererRevision), () => retryTemplateImport("./adversary/1.0.4/authoring-editor.tsx", () => import("./adversary/1.0.4/authoring-editor.tsx")).then((module) => module.adversaryAuthoring)),
  entry("敌人", "1.0.5", () => retryTemplateImport("./adversary/1.0.5/renderer.tsx", () => import("./adversary/1.0.5/renderer.tsx")).then((module) => module.adversaryRendererRevision), () => retryTemplateImport("./adversary/1.0.5/authoring-editor.tsx", () => import("./adversary/1.0.5/authoring-editor.tsx")).then((module) => module.adversaryAuthoring)),
  entry("种族", "1.0.1", () => retryTemplateImport("./ancestry/1.0.1/renderer.tsx", () => import("./ancestry/1.0.1/renderer.tsx")).then((module) => module.ancestryRendererRevision), () => retryTemplateImport("./ancestry/1.0.1/authoring-editor.tsx", () => import("./ancestry/1.0.1/authoring-editor.tsx")).then((module) => module.ancestryAuthoring), true),
  entry("护甲", "1.0.1", () => retryTemplateImport("./armor/1.0.1/renderer.tsx", () => import("./armor/1.0.1/renderer.tsx")).then((module) => module.armorRendererRevision), () => retryTemplateImport("./armor/1.0.1/authoring-editor.tsx", () => import("./armor/1.0.1/authoring-editor.tsx")).then((module) => module.armorAuthoring)),
  entry("社群", "1.0.1", () => retryTemplateImport("./community/1.0.1/renderer.tsx", () => import("./community/1.0.1/renderer.tsx")).then((module) => module.communityRendererRevision), () => retryTemplateImport("./community/1.0.1/authoring-editor.tsx", () => import("./community/1.0.1/authoring-editor.tsx")).then((module) => module.communityAuthoring), true),
  entry("领域卡", "1.0.1", () => retryTemplateImport("./domain/1.0.1/renderer.tsx", () => import("./domain/1.0.1/renderer.tsx")).then((module) => module.domainRendererRevision), () => retryTemplateImport("./domain/1.0.1/authoring-editor.tsx", () => import("./domain/1.0.1/authoring-editor.tsx")).then((module) => module.domainAuthoring), true),
  entry("环境", "1.0.1", () => retryTemplateImport("./environment/1.0.1/renderer.tsx", () => import("./environment/1.0.1/renderer.tsx")).then((module) => module.environmentRendererRevision), () => retryTemplateImport("./environment/1.0.1/authoring-editor.tsx", () => import("./environment/1.0.1/authoring-editor.tsx")).then((module) => module.environmentAuthoring)),
  entry("环境", "1.0.2", () => retryTemplateImport("./environment/1.0.2/renderer.tsx", () => import("./environment/1.0.2/renderer.tsx")).then((module) => module.environmentRendererRevision), () => retryTemplateImport("./environment/1.0.2/authoring-editor.tsx", () => import("./environment/1.0.2/authoring-editor.tsx")).then((module) => module.environmentAuthoring)),
  entry("环境", "1.0.3", () => retryTemplateImport("./environment/1.0.3/renderer.tsx", () => import("./environment/1.0.3/renderer.tsx")).then((module) => module.environmentRendererRevision), () => retryTemplateImport("./environment/1.0.3/authoring-editor.tsx", () => import("./environment/1.0.3/authoring-editor.tsx")).then((module) => module.environmentAuthoring)),
  entry("自由", "1.0.1", () => retryTemplateImport("./free/1.0.1/renderer.tsx", () => import("./free/1.0.1/renderer.tsx")).then((module) => module.freeRendererRevision), () => retryTemplateImport("./free/1.0.1/authoring-editor.tsx", () => import("./free/1.0.1/authoring-editor.tsx")).then((module) => module.freeAuthoring)),
  entry("物品", "1.0.1", () => retryTemplateImport("./item/1.0.1/renderer.tsx", () => import("./item/1.0.1/renderer.tsx")).then((module) => module.itemRendererRevision), () => retryTemplateImport("./item/1.0.1/authoring-editor.tsx", () => import("./item/1.0.1/authoring-editor.tsx")).then((module) => module.itemAuthoring), true),
  entry("职业", "1.0.1", () => retryTemplateImport("./profession/1.0.1/renderer.tsx", () => import("./profession/1.0.1/renderer.tsx")).then((module) => module.professionRendererRevision), () => retryTemplateImport("./profession/1.0.1/authoring-editor.tsx", () => import("./profession/1.0.1/authoring-editor.tsx")).then((module) => module.professionAuthoring), true),
  entry("子职业", "1.0.1", () => retryTemplateImport("./subclass/1.0.1/renderer.tsx", () => import("./subclass/1.0.1/renderer.tsx")).then((module) => module.subclassRendererRevision), () => retryTemplateImport("./subclass/1.0.1/authoring-editor.tsx", () => import("./subclass/1.0.1/authoring-editor.tsx")).then((module) => module.subclassAuthoring), true),
  entry("武器", "1.0.1", () => retryTemplateImport("./weapon/1.0.1/renderer.tsx", () => import("./weapon/1.0.1/renderer.tsx")).then((module) => module.weaponRendererRevision), () => retryTemplateImport("./weapon/1.0.1/authoring-editor.tsx", () => import("./weapon/1.0.1/authoring-editor.tsx")).then((module) => module.weaponAuthoring)),
  entry("自由", "1.0.2", () => retryTemplateImport("./free/1.0.2/renderer.tsx", () => import("./free/1.0.2/renderer.tsx")).then((module) => module.freeRendererRevision), () => retryTemplateImport("./free/1.0.2/authoring-editor.tsx", () => import("./free/1.0.2/authoring-editor.tsx")).then((module) => module.freeAuthoring)),
];

export function manifestEntryFor(templateId: string, templateVersion: string) {
  return templateFrontendManifest.find((entry) =>
    entry.templateId === templateId && entry.templateVersion === templateVersion);
}

function entry(
  templateId: string,
  templateVersion: string,
  loadRenderer: () => Promise<TrustedTemplateRenderer>,
  loadAuthoring: () => Promise<TemplateAuthoringCapability>,
  stableReferenceCard = false,
): TemplateFrontendManifestEntry {
  return { templateId, templateVersion, loadRenderer, loadAuthoring, stableReferenceCard };
}
